// <auto-generated />
namespace Quadridge.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Sun29Change : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Sun29Change));
        
        string IMigrationMetadata.Id
        {
            get { return "201807291512155_Sun29Change"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
